# COOOLa クラウド型倉庫管理システム - Spring Boot アプリケーション設定
# このファイルは開発環境、ステージング環境、本番環境で使用される設定ファイルです

# ========================================
# サーバー設定
# ========================================
server:
  port: 8080  # アプリケーションのポート番号
  servlet:
    context-path: /api  # APIのベースパス

# ========================================
# Spring Boot 設定
# ========================================
spring:
  application:
    name: cooola-warehouse-management  # アプリケーション名
  
  # ========================================
  # データベース設定
  # ========================================
  datasource:
    url: jdbc:mysql://localhost:3306/cooola_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true  # データベース接続URL
    username: cooola_user  # データベースユーザー名
    password: cooola_password  # データベースパスワード
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL JDBCドライバー
    hikari:
      maximum-pool-size: 20  # 最大コネクションプールサイズ
      minimum-idle: 5  # 最小アイドルコネクション数
      connection-timeout: 30000  # コネクションタイムアウト（30秒）
      idle-timeout: 600000  # アイドルタイムアウト（10分）
      max-lifetime: 1800000  # 最大ライフタイム（30分）
  
  # ========================================
  # JPA設定
  # ========================================
  jpa:
    hibernate:
      ddl-auto: validate  # スキーマ検証モード（本番環境推奨）
    show-sql: false  # SQLログ出力無効（本番環境）
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # MySQL 8.0用ダイアレクト
        format_sql: true  # SQLフォーマット有効
        use_sql_comments: true  # SQLコメント有効
  
  # ========================================
  # Flyway設定（データベースマイグレーション）
  # ========================================
  flyway:
    enabled: true  # Flyway有効化
    locations: classpath:db/migration  # マイグレーションSQLファイルの場所
    baseline-on-migrate: true  # 既存データベースのベースライン化
  
  # ========================================
  # セキュリティ設定
  # ========================================
  security:
    user:
      name: admin  # デフォルト管理者ユーザー名
      password: admin123  # デフォルト管理者パスワード

# ========================================
# JWT設定（JSON Web Token）
# ========================================
jwt:
  secret: cooola-jwt-secret-key-2024-warehouse-management-system  # JWT署名用シークレットキー
  expiration: 86400000  # トークン有効期限（24時間 = 86,400,000ミリ秒）

# ========================================
# AWS設定
# ========================================
aws:
  region: ap-northeast-1  # AWSリージョン（東京）
  s3:
    bucket-name: cooola-warehouse-files  # S3バケット名（ファイルストレージ）
  sqs:
    queue-url: https://sqs.ap-northeast-1.amazonaws.com/123456789012/cooola-warehouse-queue  # SQSキューURL（メッセージキュー）

# ========================================
# ログ設定
# ========================================
logging:
  level:
    com.cooola: DEBUG  # アプリケーションログレベル
    org.springframework.security: DEBUG  # Spring Securityログレベル
    org.hibernate.SQL: DEBUG  # Hibernate SQLログレベル
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Hibernateパラメータバインディングログレベル
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"  # コンソールログパターン

# ========================================
# 管理エンドポイント設定（Spring Boot Actuator）
# ========================================
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus  # 公開するエンドポイント
  endpoint:
    health:
      show-details: always  # ヘルスチェック詳細表示 